name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3  # Updated to the latest version
      with:
        java-version: 1.8

    - name: Build and test
      run: mvn clean install
